export const contents = [
  {
    id: 1,
    title: "The King Of Limbs From The Basement",
    slug: "TheKingOfLimbs",
    bigImg: "radio2.jpg",
    artist: "Radiohead",
    slugArtist: "radiohead",
    sinopsis:
      "Recorded at Maida Vale Studios, London in December 2011.Produced and Mixed by Nigel Godrich. Brass: Noel Langley, Yazz Ahmed, Clare Moss, Trevor Mires, Owen Marshall, Ben Castle, Phil Todd ",
    category: "Rock",
    video: "Radiohead - Bloom.mp4",
    year: "2011",
    duration: "60 min",
    sliderHome: false,
    trending: false,
    news: false,
    recently: false,
  },
  {
    id: 2,
    title: "In Rainbows From the Basement",
    slug: "InRainbowsFromTheBasement",
    bigImg: "radio1.jpg",
    artist: "Radiohead",
    slugArtist: "radiohead",
    sinopsis: "Recorded at The Hospital Club, London in April 2008.",
    category: "Rock",
    video: false,
    year: "2008",
    duration: "48 min",
    sliderHome: true,
    trending: true,
    news: false,
    recently: true,
  },
  {
    id: 3,
    title: "InnerSpeaker (Live From Wave House)",
    slug: "InnerSpeaker",
    bigImg: "tamaimpa.png",
    artist: "Tame Impala",
    slugArtist: "tameimpala",
    sinopsis: "Band: Kevin Parker Jay Watson Dom Simper Julien Barbagallo",
    category: "rock",
    video: false,
    year: "2022",
    duration: "62 min",
    sliderHome: true,
    trending: false,
    news: false,
    recently: false,
  },
  {
    id: 4,
    title: "Wasting Light Live from 606",
    slug: "FooFightersWastingLight",
    bigImg: "ff.jpg",
    artist: "Foo Fighters",
    slugArtist: "foofighters",
    sinopsis: " Wasting Light Live from 606.",
    category: "Rock",
    video: false,
    year: "2011",
    duration: "50 min",
    sliderHome: true,
    trending: true,
    news: false,
    recently: true,
  },
  {
    id: 5,
    title: "Live at the Royal Albert Hall",
    slug: "LiveattheRoyalAlbertHall",
    bigImg: "David_Gilmour.jpg",
    artist: "David Gilmour",
    slugArtist: "davidgilmour",
    sinopsis: " Wasting Light Live from 606.",
    category: "Full Concert",
    video: false,
    year: "2006",
    duration: "152 min",
    sliderHome: true,
    trending: false,
    news: true,
    recently: false,
  },
  {
    id: 6,
    title: "LIVE SET",
    slug: "WOS_livesession",
    bigImg: "wosliveset.png",
    artist: "WOS",
    slugArtist: "wos",
    sinopsis: " Prod. EVLAY (Alma Dinamita, Freestyle, Fresco)",
    category: "Live session",
    video: false,
    year: "2022",
    duration: "11 min",
    sliderHome: true,
    trending: false,
    news: true,
    recently: false,
  },
  {
    id: 7,
    title: "Claro Sessions",
    slug: "tiagopzkclarosession",
    bigImg: "taigoclaroses.jpg",
    artist: "TIAGO PZK",
    slugArtist: "tiagopzk",
    sinopsis:
      "Claro y Motorola presentan a TIAGO PZK en un show exclusivo para Claro Sessions.",
    category: "Live session",
    video: false,
    year: "2022",
    duration: "39 min",
    sliderHome: true,
    trending: false,
    news: true,
    recently: false,
  },
];
