export const movies = [
  {
    id: 1,
    title: "The King Of Limbs From The Basement",
    slug: "TheKingOfLimbs",
    bigImg: "radio2.jpg",
    director: "Radiohead",
    sinopsis:
      "Recorded at Maida Vale Studios, London in December 2011.Produced and Mixed by Nigel Godrich. Brass: Noel Langley, Yazz Ahmed, Clare Moss, Trevor Mires, Owen Marshall, Ben Castle, Phil Todd ",
    category: "Rock",
    year: "2011",
    duration: "60 min",
    sliderHome: true,
    trending: true,
    nuevas: false,
    favoritas: false,
  },
  {
    id: 2,
    title: "In Rainbows From the Basement",
    slug: "InRainbowsFromTheBasement",
    bigImg: "radio1.jpg",
    director: "Radiohead",
    sinopsis: "Recorded at The Hospital Club, London in April 2008.",
    category: "Rock",
    year: "2008",
    duration: "63 min",
    sliderHome: true,
    trending: true,
    nuevas: false,
    favoritas: false,
  },
  {
    id: 3,
    title: "InnerSpeaker (Live From Wave House)",
    slug: "elcaballerooscuro",
    bigImg: "tamaimpa.png",
    director: "Tame Impala",
    sinopsis: "Band: Kevin Parker Jay Watson Dom Simper Julien Barbagallo",
    category: "rock",
    year: "2022",
    duration: "62 min",
    sliderHome: true,
    trending: true,
    nuevas: false,
    favoritas: false,
  },
  {
    id: 4,
    title: "Wasting Light Live from 606",
    slug: "FooFightersWastingLight",
    bigImg: "ff.jpg",
    director: "Foo Fighters",
    sinopsis: " Wasting Light Live from 606.",
    category: "Rock",
    year: "2011",
    duration: "50 min",
    sliderHome: true,
    trending: true,
    nuevas: false,
    favoritas: true,
  },
  {
    id: 5,
    title: "American Beauty",
    slug: "americanbeauty",
    bigImg: "american-beauty-kmnh-u907863933720k-1248x770atrc-1657889036.jpg",
    director: "Sam Mendes",
    sinopsis:
      "La película de Sam Mendes con guión del creador de 'A dos metros bajo tierra', Alan Ball, cuestionó el american way of life con un drama familiar repleto de imágenes para el recuerdo, como la famosa escena de los pétalos de rosa o la bolsa bailando con el viento.",
    category: "Comedia",
    year: "1999",
    duration: "120 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: false,
  },
  {
    id: 6,
    title: "Vengadores: Infinity War",
    slug: "vengadoresinfinitywar",
    bigImg: "infinity-war-1656085938.jpg",
    director: "Anthony Russo, Joe Russo",
    sinopsis:
      "Reúne en una monumental entrega todo lo que ha hecho grande a Marvel hasta ahora: luchas épicas, batallas galácticas, one-liners demoledores, el splash page cinemático, efectos visuales pluscuamperfectos y un sentido único del espectáculo, capaz de ser grandilocuente y enfático pero sin perder nunca un distanciamiento irónico marca de la casa que conecta directamente con el público, sea fan o no",
    category: "Ciencia ficción",
    year: "2018",
    duration: "121 min",
    sliderHome: false,
    trending: true,
    nuevas: false,
    favoritas: false,
  },
  {
    id: 7,
    title: "El resplandor",
    slug: "elresplandor",
    bigImg: "el-resplandor-1656085938.jpg",
    director: "Stanley Kubrick",
    sinopsis:
      "Basada (muy libremente) en la novela de Stephen King (para desgracia del escritor, que siempre renegó de esta adaptación), es un viaje a la locura del aislamiento y la historia colectiva escrita en sangre que ha generado numerosas teorías y análisis durante más de cuarenta años. Y aún hay muchos de sus detalles que carecen de respuesta, imágenes que ni el documental 'Room 237' ha podido resolver. Es parte de su encanto, y de por qué tiene algunas de las frases y escenas más famosas de todos los tiempos",
    category: "Terror",
    year: "1980",
    duration: "125 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: false,
  },
  {
    id: 8,
    title: "Django desencadenado",
    slug: "djangodesencadenado",
    bigImg: "django-1655132129.jpg",
    director: "Quentin Tarantino",
    sinopsis:
      "Con sus disquisiciones lingüísticas segundos antes de un tiroteo o el pulso sobre una fórmula de cortesía que precede al clímax de violencia, 'Django desencadenado' es, quizá, el western que mayor atención jamás haya prestado al lenguaje verbal: los zooms y reencuadres de la puesta en escena parecen funcionar como contrapunto estilístico a esa obsesión por la(s) forma(s). Con una trama que pone especial énfasis en la representación y juega a fondo la carta del humor (la escena del Ku Klux Klan),",
    category: "Drama",
    year: "2012",
    duration: "132 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: true,
  },
  {
    id: 10,
    title: "En busca del arca perdida",
    slug: "enbuscadelarcaperdida",
    bigImg: "en-busca-del-arca-perdida-1655132129.jpg",
    director: "Steven Spielberg",
    sinopsis:
      "Un verdadero clásico del moderno cine de aventuras, en el que Spielberg rescató la tradición del género en una hábil adaptación a los nuevos tiempos. Basado en un argumento de George Lucas y Philip Kaufman, desarrolla una imaginativa trama, conducida con envidiable seguridad. Su éxito generó diversas secuelas, una serie televisiva e innumerables imitaciones.",
    category: "Ciencia ficción",
    year: "2019",
    duration: "110 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: false,
  },

  {
    id: 11,
    title: "Memento",
    slug: "Memento",
    bigImg: "memento-1635529529.jpg",
    director: "Christopher Nolan",
    sinopsis:
      "A no ser que el lector padezca la enfermedad del protagonista de 'Memento' y sea capaz de olvidar esta crítica tras haberla leído, es mejor que detenga de inmediato su lectura si quiere evitar que se le desvelen algunas peculiaridades de esta audaz, radical y sorpresiva trama",
    category: "Drama",
    year: "1998",
    duration: "90 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: false,
  },

  {
    id: 12,
    title: "Top Gun: Maverick",
    slug: "topgunmaverick",
    bigImg: "top-gun-2-maverick-tom-cruise-jennifer-connelly-1617788063.jpg",
    director: "Joseph Kosinski",
    sinopsis:
      "La eterna juventud de Cruise abre una brecha entre la nueva Top Gun y otras operaciones de rescate de hitos fílmicos ochenteros. Así, mientras los revivals de Indiana Jones, Rocky o Star Wars ponían el acento en la idea del relevo, Top Gun: Maverick sitúa al héroe “viejoven” en el centro de todas las disputas. Cruise noparece necesitar herederos, igual que no requiere de dobles de acción: verle resistir violentas fuerzas G es casi tan excitante como asistir a los memorables esprints de Ethan Hunt",
    category: "Drama",
    year: "2022",
    duration: "122 min",
    sliderHome: false,
    trending: true,
    nuevas: true,
    favoritas: false,
  },

  {
    id: 13,
    title: "Hara-Kiri",
    slug: "harakiri",
    bigImg: "harakiri-1595531688.jpg",
    director: "Masaki Kobayashi",
    sinopsis:
      "Obra cumbre del género y la que mejor se plantea el significado del honor. Narrada en flashback, un veterano ronin se sienta en medio del patio de una prestigiosa orden samurái solo para contarles cómo obligaron a morir a su yerno por una deshonra que no debería serlo, para, a continuación, intentar acabar con todos",
    category: "Drama",
    year: "1964",
    duration: "94 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: false,
  },

  {
    id: 14,
    title: "Whiplash",
    slug: "whiplash",
    bigImg: "35-whiplash.jpg",
    director: "Damien Chazelle",
    sinopsis:
      "Lejos de conformarse con realizar un estudio del maltrato psicológico, esta parábola cerebral a ritmo de jazz se revela como incómoda refexión sobre la necesidad de sacrificar cuerpo y alma en el sagrado nombre del Arte",
    category: "Documental",
    year: "2014",
    duration: "143 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: true,
  },

  {
    id: 15,
    title: "Psicosis",
    slug: "psicosis",
    bigImg: "41-psicosis.jpg",
    director: "Alfred Hitchcock",
    sinopsis:
      "Una de las muestras más depuradas del talento de Hitchcock para montar una apasionante intriga a partir del más simple de los artificios. En este sentido, la convención psicoanalítica de la narración de Robert Block queda desmontada por el propio desarrollo de la historia, quedando sólo en pie su magistral y rigurosa capacidad de fabulación",
    category: "Terror",
    year: "1960",
    duration: "87 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: false,
  },

  {
    id: 16,
    title: "El viaje de Chihiro",
    slug: "elviajedevhihiro",
    bigImg: "32-vijedechichiro.jpg",
    director: "Hayao Miyazaki",
    sinopsis:
      "Libérrima, intensa y deslumbrante, es una de esas películas que inventan su realidad a cada plano, tensando la capacidad de asombro del espectador, sometido a una experiencia equivalente a una sobredosis del Grandville más alucinatorio inyectada por un calígrafo oriental empeñado en reinventar el alfabeto",
    category: "Documental",
    year: "2001",
    duration: "122 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: false,
  },

  {
    id: 17,
    title: "Regreso al futuro",
    slug: "regresoalfuturo",
    bigImg: "regreso-al-futuro-1543591177.jpg",
    director: "Steven Spielberg",
    sinopsis:
      "¿Qué tendrá 'Regreso al futuro' para que pase el tiempo y siga siendo una de las películas de viajes y bucles temporales que mejor envejece.",
    category: "Comedia",
    year: "1985",
    duration: "113 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: true,
  },
  {
    id: 18,
    title: "Interstellar",
    slug: "interstellar",
    bigImg: "interestellar.jpg",
    director: "Christopher Nolan",
    sinopsis:
      "De entre las mejores películas de ciencia ficción de todos los tiempos, pocas se toman tan en serio el funcionamiento del cosmos como esta.",
    category: "Ciencia ficción",
    year: "2014",
    duration: "154 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: true,
  },

  {
    id: 19,
    title: "La milla verde",
    slug: "lamillaverde",
    bigImg: "42-lamillaverde.jpg",
    director: "Frank Darabont",
    sinopsis:
      "Aunque hubiera podido ser también un excelente Grandes relatos televisivo, es un convincente espectáculo cinematográfico a la manera clásica. Emotivo y melodramático, pero también sutil. En él se reconoce la pervivencia del porqué el folletín, hace cien años y, probablemente, durante los próximos cien, cuando es inteligente y hábil, sigue y seguirá conquistando a lectores y espectadores",
    category: "Documental",
    year: "1999",
    duration: "153 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: false,
  },
  {
    id: 20,
    title: "Salvar al soldado Ryan",
    slug: "salvaralsoldadoryan",
    bigImg: "38-salvarsoldadoryan.jpg",
    director: "Steven Spielberg",
    sinopsis:
      "La película entronca con la reflexión épica de clásicos como 'A Walk in the Sun' o 'La colina de los diablos de acero', no tan interesados en discutir ta pertinencia e inmoralidad de la guerra, como en profundizar en la psicología del individuo ante la situación límite por excelencia. la postura ideológica de Spielberg resulta ambigua y discutible, es decir, dotada de una riqueza abierta a la discusión. Una obra compleja a la que es imposible asistir sin sentirse removido por la ferocidad de sus imágenes",
    category: "Documental",
    year: "1998",
    duration: "131 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: false,
  },

  {
    id: 21,
    title: "Ciudad de Dios",
    slug: "ciudaddedios",
    bigImg: "22-ciudaddedios.jpg",
    director: "Fernando Meirelles",
    sinopsis:
      "Ciudad de Dios' es una de las películas latinoamericanas más interesantes de los últimos tiempos. Y no solo por el tema que toca, sino por la forma atrevida, violenta pero estéticamente brillante que ha escogido Fernando Meirelles para lanzar un toque de atención sobre una situación que día a día se hace insostenible en las grandes ciudades latinoamericanas",
    category: "Documental",
    year: "2002",
    duration: "110 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: false,
  },
  {
    id: 22,
    title: "El silencio de los corderos",
    slug: "elsilenciodeloscorderos",
    bigImg: "28-elsilenciodeloscorderos.jpg",
    director: "Jonathan Demme",
    sinopsis:
      "Es una adaptación de una excelente novela de Thomas Harris que no llega a extraer toda la complejidad del texto, ofreciendo una lectura impactante pero algo reduccionista de la misma. La fascinanción por el Mal es el detonante de un juego no siempre sutil pero muy bien cimentado en la memorable interpretación de Anthony Hopkins",
    category: "Terror",
    year: "1991",
    duration: "123 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: false,
  },
  {
    id: 23,
    title: "Seven",
    slug: "seven",
    bigImg: "25-seven.jpg",
    director: "David Fincher",
    sinopsis:
      "Seven' no aguanta un análisis detallado o naturalista del guión. Hay muchas cosas inverosímiles o simplemente incoherentes. Pero de esa incoherencia saca Fincher la materia prima para hacer un cine en el que alterna momentos de ritmo lento e intimista, con secuencias trepidantes, sin que entre unas y otras haya una fractura, sino una continuidad absolutamente lógica",
    category: "Terror",
    year: "1995",
    duration: "109 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: false,
  },
  {
    id: 24,
    title: "Matrix",
    slug: "matrix",
    bigImg: "21-matrix.jpg",
    director: "Andy Wachowski, Larry Wachowski",
    sinopsis:
      "Combinando ecos del más espectacular cine de acción oriental con una marcada sensibilidad cyberpunk y con las cabriolas visuales del videojuego más extremo, los Wachowski han facturado la película de ciencia-ficción más inteligente desde '12 Monos' o 'Crash', han sabido trasladar magníficamente a la pantalla la estética (y la ética) de Darrow y, en suma, han hecho historia. ¿Se puede pedir más?",
    category: "Ciencia ficción",
    year: "1999",
    duration: "143 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: false,
  },
  {
    id: 25,
    title: "El imperio contraataca",
    slug: "elimperiocontraataca",
    bigImg: "13-elimperiocontraataca.jpg",
    director: "Irvin Kershner",
    sinopsis:
      "Segunda entrega de la saga iniciada en la que se evidencia un descenso de interés en relación con su precedente. Pese a conservar parte de su garra narrativa, la parafernalia de los efectos especiales se impone en exceso sobre la coherencia narrativa",
    category: "Ciencia ficción",
    year: "1980",
    duration: "132 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: false,
  },
  {
    id: 26,
    title: "Origen",
    slug: "origen",
    bigImg: "12-origen.jpg",
    director: "Christopher Nolan",
    sinopsis:
      "Arrolladora demostración de virtuosismo estilístico, 'Origen' reúne con espíritu de preciso delineante numerosas citas del género fantacientífico, jamás como una mera acumulación de guiños: Stanley Kubrick está no solamente en ese hotel sin gravedad que se diría estación espacial, sino en el laberinto que Ellen Page dibuja, y en el laberinto que el astuto realizador crea a base de yuxtaponer los diversos sueños, las diversas realidades, manejando secuencias irresistibles de alta tensión",
    category: "Ciencia ficción",
    year: "2012",
    duration: "203 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: true,
  },
  {
    id: 27,
    title: "El club de la lucha",
    slug: "Elclubdelalucha",
    bigImg: "10-elclubdelalucha.jpg",
    director: "David Fincher",
    sinopsis:
      "El discurso de Fincher, recorrido por un malévolo sentido del humor, es del todo nihilista: hay que derrocar las bases de la sociedad occidental, hay que dinamitar los bancos, la Bolsa, las grandes corporaciones. Que Fincher convierta esa fascinación por la catástrofe en un elogio del suicidio colectivo es solo una de las muchas licencias poéticas que se toma esta excepcional película terrorista, un moderno y necesario manifiesto anarquista",
    category: "Comedia",
    year: "1999",
    duration: "91 min",
    sliderHome: false,
    trending: true,
    nuevas: false,
    favoritas: true,
  },
  {
    id: 28,
    title: "Forrest Gump",
    slug: "forrestgump",
    bigImg: "14-forrestgump.jpg",
    director: "Robert Zemeckis",
    sinopsis:
      "Forrest Gump' (el segundo Oscar de Tom Hanks) se ganó el corazón de los estadounidenses de las últimas tres décadas. Este chico de bajo coeficiente intelectual, pero admirable inocencia y buen corazón, consiguió llamar la atención con su aplastante sentido común en contraste con la profunda crisis de valores de la sociedad",
    category: "Comedia",
    year: "1994",
    duration: "143 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: true,
  },
  {
    id: 29,
    title: "El señor de los anillos: La comunidad del anillo",
    slug: "Lacomunidaddelanillo",
    bigImg: "11-elsenordelosanillos.jpg",
    director: "Peter Jackson",
    sinopsis:
      "Espectáculo-mamut sin tacha aparente, 'La Comunidad del Anillo' logra ser una película avasalladoramente física (nada hay en ella de aséptico videojuego, pese al gran tonelaje de magia digital), en la que los actores tienen espacio, poder y capacidad para construir sus personajes o bordar momentos inmortales",
    category: "Ciencia ficción",
    year: "2001",
    duration: "140 min",
    sliderHome: false,
    trending: true,
    nuevas: false,
    favoritas: false,
  },
  {
    id: 30,
    title: "Pulp Fiction",
    slug: "pulpfiction",
    bigImg: "05-pulpfiction.jpg",
    director: "Quentin Tarantino",
    sinopsis:
      "¿Es 'Pulp Fiction' la mejor película de Quentin Tarantino? Según IMdB, sí, aunque hay quien encuentra 'Érase vez en Hollywood...' su obra maestra definitiva. Lo que no se puede negar es que 'Pulp Fiction' tiene todas las señales de estilo del cine de Quentin Tarantino, y por eso la amamos",
    category: "Comedia",
    year: "1994",
    duration: "104 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: true,
  },
  {
    id: 31,
    title: "La lista de Schindler",
    slug: "lalistadeSchindler",
    bigImg: "09-lista-schindler.jpg",
    director: "Steven Spielberg",
    sinopsis:
      "Una nueva mirada sobre el Holocausto judío, en la que Spielberg puso toda la carne en el asador para desarrollar una de tantas historias sobre el oprobio que supuso el nazismo. Su principal problema reside en el personaje central, presentado como una especie de héroe cuando no fue más que un vividor que si salvó a los judíos fue para aprovecharse de ellos. Esta salvedad no impide que el conjunto tenga una fuerza poco común dentro del cine moderno",
    category: "Documental",
    year: "1993",
    duration: "102 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: false,
  },
  {
    id: 32,
    title: "El caballero oscuro",
    slug: "elcaballerooscuro",
    bigImg: "04-elcaballerooscuro.jpg",
    director: "Christopher Nolan",
    sinopsis:
      "'El Caballero Oscuro' desmiente su condición inicial de blockbuster revienta taquilla con una serie de argumentos estéticos, interpretativos, emocionales, filosóficos e ideológicos que la propulsan muy por encima de cualquier otra adaptación de cómic que hayamos visto hasta la fecha. Sin renunciar a las concesiones propias del cine espectáculo, pero dotadas éstas de una elegancia, tenebrosidad y radicalidad alejada de la órbita mainstream.",
    category: "Drama",
    year: "2008",
    duration: "108 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: true,
  },
  {
    id: 33,
    title: "Morbius",
    slug: "morbius",
    bigImg: "morbius-official-trailer-1635860706.jpg",
    director: "Daniel Espinosa",
    sinopsis:
      "Hhistoria ambientada en el universo de Spider-Man y centrada en uno de sus villanos más icónicos: Morbius. Jared Leto se meterá en la piel de este vampiro en esta cinta de terror que no ha convencido a los críticos, y con razón: le falta tensión y nervio, algo que provoca que sea una película rutinaria, convencional y hasta un poco aburrida. Una decepción para el universo Marvel en Sony, que cada vez está más cerca del Universo Cinematográfico de Marvel.",
    category: "Ciencia ficción",
    year: "2022",
    duration: "123 min",
    sliderHome: false,
    trending: true,
    nuevas: true,
    favoritas: false,
  },
  {
    id: 34,
    title: "Muerte en el Nilo",
    slug: "muerteenelnilo",
    bigImg: "muerte-en-el-nilo-fotogramas-1628081297.jpg",
    director: "Kenneth Branagh",
    sinopsis:
      "Un remake de otro clásico de Agatha Christie tras la notable, aunque no extraordinaria, 'Asesinato en el Orient Express'. Y todo lo que tenía aquella de cuestionable vuelve a repetirse en esta secuela, 'Muerte en el Nilo'. El cineasta vuelve a convertirse en el detective Hércules Poirot para descubrir en otro viaje, ahora en un barco fluvial en Egipto, quién es el sospechoso del asesinato de una aristócrata americana.",
    category: "Drama",
    year: "2022",
    duration: "91 min",
    sliderHome: false,
    trending: false,
    nuevas: true,
    favoritas: false,
  },
  {
    id: 35,
    title: "Moonfall",
    slug: "Moonfall",
    bigImg: "captura-de-pantalla-2022-02-02-a-las-10-31-56-1643794328.jpg",
    director: "Patrick Wilson",
    sinopsis:
      "Una de las mejores películas de catástrofes que veremos este año. En este nuevo desastre mundial de Roland Emmerich, rey del cine de catástrofes tras 'El día de mañana' y '2012', es la Luna la que corre peligro: como su propio nombre indica, la película nos mostrará cómo la Luna amenaza con estrellarse contra la Tierra. Halle Berry y Patrick Wilson capitanean el reparto de esta película de acción catastrófica tan típica de Emmerich, pero que no logra igualar sus grandes éxitos del pasado. ¿Por qué nos gustan tanto las películas de catástrofes?",
    category: "Drama",
    year: "2022",
    duration: "101 min",
    sliderHome: false,
    trending: false,
    nuevas: true,
    favoritas: false,
  },
  {
    id: 36,
    title: "Agentes 355",
    slug: "agentes355",
    bigImg: "the-355-poster-1601962918.jpeg",
    director: "Jason Bourne",
    sinopsis:
      "El año comenzó con una reunión de agentes secretas internacionales. Escrita por Theresa Rebeck y Simon Kinberg y dirigida por este mismo, la historia se pone en marcha cuando un arma ultrasecreta cae en manos de mercenarios. Un grupo de élite (formado por Penélope Cruz, Diane Kruger, Jessica Chastain, Lupita Nyong'o y Fan Bingbing) pasarán por París, Marruecos o Shanghai en una misión ultrasecreta para salvar al mundo, y a sus seres queridos.",
    category: "Comedia",
    year: "2022",
    duration: "111 min",
    sliderHome: false,
    trending: false,
    nuevas: true,
    favoritas: false,
  },
  {
    id: 37,
    title: "Lightyear",
    slug: "Lightyear",
    bigImg: "lightyear-chris-evans-1649935658.jpg",
    director: "Calma Segura",
    sinopsis:
      "Mientras las mejores películas recientes de Pixar (como 'Red', mucho mejor posicionada en esta lista) se van directas a Disney+, su película más formulaica, 'Lightyear', ha tenido su estreno en cines. Aun así, como dice la crítica de 'Ligthyear', su poder resulta de su gozosa apuesta por la aventura más tradicional, del amor que se respira hacia la ciencia-ficción más referencial, y, por supuesto, en eso son insuperables, de su sabio equilibrio con lo tronchante, lo tierno y lo dramático.",
    category: "Comedia",
    year: "2022",
    duration: "73 min",
    sliderHome: false,
    trending: false,
    nuevas: true,
    favoritas: false,
  },
  {
    id: 38,
    title: "Veneciafrenia",
    slug: "Veneciafrenia",
    bigImg: "veneciafrenia-alex-de-la-iglesia-1635420356.jpg",
    director: "Álex de la Iglesia",
    sinopsis:
      "Venecia se convierte en el escenario de un slasher en esta nueva película de Álex de la Iglesia. 'Veneciafrenia' está protagonizada por un grupo de turistas españoles que viajan a la ciudad italiana para pasar un buen rato y disfrutar de sus vacaciones, pero pronto tendrán que luchar por su supervivencia entre las góndolas.",
    category: "Terror",
    year: "2022",
    duration: "121 min",
    sliderHome: false,
    trending: false,
    nuevas: false,
    favoritas: true,
  },
];
