export const artist = [
  {
    id: 1,
    title: "Radiohead",
    slug: "radiohead",
    logo: "radiohead_logoOso.jpg",
    bigpic: "radioheadlandscape.png",
    sinopsis:
      "Radiohead es una banda de rock alternativo formada en Oxford, Reino Unido en 1985. La banda está compuesta por Thom Yorke (vocalista, guitarra y teclado), Jonny Greenwood (guitarra, teclado y oud), Ed O'Brien (guitarra y coros), Colin Greenwood (bajo y teclado) y Philip Selway (batería y coros). La banda es conocida por su música experimental y su sonido en constante evolución a lo largo de su carrera. Su música incorpora elementos de rock, pop, electrónica, jazz y folk y su letra a menudo trata temas políticos y sociales. Radiohead ha vendido más de 30 millones de álbumes en todo el mundo y es conocida por álbumes como 'OK Computer', 'Kid A' y 'In Rainbows'.",
    category: "Rock",
    facebook: "radiohead",
    instagram: "radiohead",
    twitter: "radiohead",
    spotify: "radiohead",
    youtube: "radiohead",
    donate: false,
  },
  {
    id: 2,
    title: "Tame Impala",
    slug: "tameimpala",
    logo: "tameimpalab0.jpg",
    bigpic: "tame-impala.webp",
    sinopsis:
      "Recorded at Maida Vale Studios, London in December 2011.Produced and Mixed by Nigel Godrich. Brass: Noel Langley, Yazz Ahmed, Clare Moss, Trevor Mires, Owen Marshall, Ben Castle, Phil Todd ",
    category: "Rock",
    facebook: false,
    instagram: false,
    twitter: false,
    spotify: false,
    youtube: false,
    donate: false,
  },
  {
    id: 7,
    title: "Arizona Moon",
    slug: "arizonamoon",
    logo: "violet-moon.png",
    bigpic: "arizonaband.jpeg",
    sinopsis:
      "Somos una banda nacida en 2021 hacemos musica rock mezclado con un poco de tecno/funk, tenemos 4 temas y queremos grabar un video de una session, nos ayudas donandones para que grabemos un video. ",
    category: "trap",
    facebook: false,
    instagram: "arizonamoonok",
    twitter: false,
    spotify: "arizonamoonok",
    youtube: "arizonamoonok",
    donate: true,
  },
  {
    id: 3,
    title: "Foo Fighters",
    slug: "foofighters",
    logo: "fflogo.png",
    bigpic: "Foo-Fighters.webp",
    sinopsis:
      "Recorded at Maida Vale Studios, London in December 2011.Produced and Mixed by Nigel Godrich. Brass: Noel Langley, Yazz Ahmed, Clare Moss, Trevor Mires, Owen Marshall, Ben Castle, Phil Todd ",
    category: "Rock",
    facebook: false,
    instagram: false,
    twitter: false,
    spotify: false,
    youtube: false,
    donate: false,
  },
  {
    id: 4,
    title: "David Gilmour",
    slug: "davidgilmour",
    logo: "davidgil.jpg",
    bigpic: "david-gilberg.jpeg",
    sinopsis:
      "Recorded at Maida Vale Studios, London in December 2011.Produced and Mixed by Nigel Godrich. Brass: Noel Langley, Yazz Ahmed, Clare Moss, Trevor Mires, Owen Marshall, Ben Castle, Phil Todd ",
    category: "Rock",
    facebook: false,
    instagram: false,
    twitter: false,
    spotify: false,
    youtube: false,
    donate: false,
  },
  {
    id: 5,
    title: "WOS",
    slug: "wos",
    logo: "wosfms.jpg",
    bigpic: "Wos.jpg",
    sinopsis:
      "Recorded at Maida Vale Studios, London in December 2011.Produced and Mixed by Nigel Godrich. Brass: Noel Langley, Yazz Ahmed, Clare Moss, Trevor Mires, Owen Marshall, Ben Castle, Phil Todd ",
    category: "trap",
    facebook: false,
    instagram: "wosito",
    twitter: false,
    spotify: false,
    youtube: false,
    donate: false,
  },
  {
    id: 6,
    title: "TIAGO PZK",
    slug: "tiagopzk",
    logo: "tiagoapzk.png",
    bigpic: "Tiago-PZK.jpg",
    sinopsis:
      "Recorded at Maida Vale Studios, London in December 2011.Produced and Mixed by Nigel Godrich. Brass: Noel Langley, Yazz Ahmed, Clare Moss, Trevor Mires, Owen Marshall, Ben Castle, Phil Todd ",
    category: "trap",
    facebook: false,
    instagram: false,
    twitter: false,
    spotify: false,
    youtube: false,
    donate: false,
  },
];
