export const contents = [
  {
    id: 1,
    title: "The King Of Limbs From The Basement",
    slug: "TheKingOfLimbs",
    bigImg: "radio2.jpg",
    director: "Radiohead",
    sinopsis:
      "Recorded at Maida Vale Studios, London in December 2011.Produced and Mixed by Nigel Godrich. Brass: Noel Langley, Yazz Ahmed, Clare Moss, Trevor Mires, Owen Marshall, Ben Castle, Phil Todd ",
    category: "Rock",
    year: "2011",
    duration: "60 min",
    sliderHome: true,
    trending: true,
    nuevas: true,
    favoritas: false,
  },
  {
    id: 2,
    title: "In Rainbows From the Basement",
    slug: "InRainbowsFromTheBasement",
    bigImg: "radio1.jpg",
    director: "Radiohead",
    sinopsis: "Recorded at The Hospital Club, London in April 2008.",
    category: "Rock",
    year: "2008",
    duration: "63 min",
    sliderHome: true,
    trending: true,
    nuevas: false,
    favoritas: false,
  },
  {
    id: 3,
    title: "InnerSpeaker (Live From Wave House)",
    slug: "elcaballerooscuro",
    bigImg: "tamaimpa.png",
    director: "Tame Impala",
    sinopsis: "Band: Kevin Parker Jay Watson Dom Simper Julien Barbagallo",
    category: "rock",
    year: "2022",
    duration: "62 min",
    sliderHome: true,
    trending: true,
    nuevas: false,
    favoritas: false,
  },
  {
    id: 4,
    title: "Wasting Light Live from 606",
    slug: "FooFightersWastingLight",
    bigImg: "ff.jpg",
    director: "Foo Fighters",
    sinopsis: " Wasting Light Live from 606.",
    category: "Rock",
    year: "2011",
    duration: "50 min",
    sliderHome: true,
    trending: true,
    nuevas: false,
    favoritas: true,
  },
];
